# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_CellBarcode_wrappers", use_symbols = TRUE, package_name = "CellBarcode")

#' @usage NULL
#' @useDynLib CellBarcode, .registration = TRUE
NULL

#' Parse 10X SAM file
#' 
#' @param in_file_path A string, define the un-mapped sequences
#' @param regex_str A string, define the regular expression to match the barcode sequence.
#' @param cell_barcode_tag A string, define the tag of 10X cell barcode field in sam file.
#' @param umi_tag A string, define the tag of UMI field in the sam file.
#' @return A list containing two data frames:
#'   - `barcode_df`: with columns `cell_barcode`, `umi`, `barcode_seq`, and `count`.
#'   - `raw_reads_df`: with columns `cell_barcode` and `count`.
parse_10x_sam <- function(in_file_path, regex_str, cell_barcode_tag, umi_tag) .Call(wrap__parse_10x_sam, in_file_path, regex_str, cell_barcode_tag, umi_tag)

#' Sequence clustering using Levenshtein or Hamming distance
#' 
#' @param seq A string vector of sequences.
#' @param count An integer vector corresponding to sequence counts.
#' @param count_threshold A Integer Threshold to consider a sequence as true barcode.
#' @param dist_threshold A Integer Distance threshold for clustering.
#' @param depth_fold_threshold Fold change threshold for merging.
#' @param dist_method Distance method: 2 for Levenshtein, otherwise Hamming.
#' @param cost A vector of three integers for Levenshtein distance costs, the order is insert, delete, replace.
#' 
#' @return A list with two data frames:
#' - `seq_freq_tab`: Corrected sequence frequency table.
#' - `link_tab`: Clustering process record.
seq_correct <- function(seq, count, count_threshold, dist_threshold, depth_fold_threshold, dist_method, cost) .Call(wrap__seq_correct, seq, count, count_threshold, dist_threshold, depth_fold_threshold, dist_method, cost)

read_fastq <- function(in_file_path) .Call(wrap__read_fastq, in_file_path)

read_fastq_gz <- function(in_file_path) .Call(wrap__read_fastq_gz, in_file_path)

read_fastq_gz2 <- function(in_fq1, in_fq2) .Call(wrap__read_fastq_gz2, in_fq1, in_fq2)


# nolint end
