# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hamming Distance
#' 
#' This function return hamming distance between two string.
#' If the two string do not have the same length, it will
#' return 999.
#'
#' @param s1, s2 two string
NULL

#' Sequence clustering
#' 
#' This function will merge the UMIs by using the 
#' hamming distance. If two UMIs have hamming distance
#' no more than 1, only the UMI with more reads
#' will be kept.
#' 
#' This function will return the corrected UMI list.
#'
#' @param seq A string vector
#' @param count An integer vector with the same order and length of UMI
#' @param count_threshold An integer the maximum barcodes number
#' @param hamm_dist_threshold An integer the hamming distance threshold
seq_correct <- function(seq, count, count_threshold, hamm_dist_threshold) {
    .Call('_Bc_seq_correct', PACKAGE = 'Bc', seq, count, count_threshold, hamm_dist_threshold)
}

